### ISSUE TITLE
default for context-fill instead of currentColor

### ISSUE THREAD

**Issue by dokax** [iconify/icon-sets#100]
currentColor does't has effect when i use icon in css, i have to change the value to context-fill everytime i download an icon.
and the icon size is 1em if you didn't set a size, i mean if the icon default size is 20px, then i should get 20px icon if i didn't set the size.

**Comment by cyberalien** [comment]
Default size is set to 1em for few reasons:

Many icons are not designed with small size, they are designed at something like 512px grid, expecting to be downscaled 16 or 32 (then what value would you expect it to use: 16 or 32 ?). Some bad icon sets (mostly ones designed to work as icon fonts) aren't even designed for any specific grid in mind, having seemingly random height.

Then when icons are used, it would be nice if icons just worked regardless of which icon set it is from. So if one icon is from 20px grid set, another icon is from 24px grid, when inserted in same row (such as navigation or whatever) they should look similar, 1em height makes it possible.

As for color, what is `context-fill` you are talking about?
