### ISSUE TITLE
Add GravityUI icon set

### ISSUE THREAD

**Issue by Dimava** [iconify/icon-sets#101]
License: MIT
Website: https://gravity-ui.com/icons , https://gravity-ui.com/libraries/icons
Repo: https://github.com/gravity-ui/icons
Figma: https://www.figma.com/community/file/1271150067798118027/Gravity-UI-Design-System-(Beta)
cc @amje as the GravityUI icons maintainer

**Comment by cyberalien** [comment]
Excellent icon set. Added.

It will appear in icon sets list on Friday after automatic update script is ran.
