### ISSUE TITLE
Icon Set Proposal: SuperTinyIcons

### ISSUE THREAD

**Issue by hyperupcall** [iconify/icon-sets#102]
[SuperTinyIcons](https://github.com/edent/SuperTinyIcons) might be a good addition to have in this icon set. It's quite popular.

I tried to find documentation to find it myself, but it doesn't seem like that's possible? Looking at `iconify/icon-sets` and `iconify/iconify`, I could find no source code to generate the icon sets for this project?

**Comment by cyberalien** [comment]
Sorry, no. That is a very bad set. It is just a set of various logos, very loosely resized (some have a lot of padding on sides, some have little padding, some don't have any padding at all) and placed in 512x512 square.

There are plenty of logo sets available that are much better quality.

As for code, script that updates packages is not public, but all functions used by it are: https://github.com/iconify/tools
