### ISSUE TITLE
Add Framework7 icon set

### ISSUE THREAD

**Issue by mueller-ma** [iconify/icon-sets#104]
Hi,

I'd like to see the Framework7 icons at iconify :)

- https://framework7.io/icons/
- https://github.com/framework7io/framework7-icons

**Comment by cyberalien** [comment]
Added.

Update script already ran earlier today, so icon set will appear only on next run on Monday.

However, you can already use it with packages that use `@iconify-json/f7` set, such as UnoCSS and Unplugin Icons. Only packages that rely on API will require waiting for API update on Monday.
