### ISSUE TITLE
Add Custom brand Icons

### ISSUE THREAD

**Issue by elax46** [iconify/icon-sets#106]
Hi, as asked by user [@schmierlappe](https://github.com/elax46/custom-brand-icons/issues/533) 

I request the inclusion of my icon set!

- https://github.com/elax46/custom-brand-icons/tree/main/icon-svg
- prefix `cbi`

ps the icons to be inserted are only those present in the main branch, the dev branch is used for testing before the final release

**Comment by cyberalien** [comment]
Sure, it can be added.

Though I do have questions.

1. Icon size is inconsistent. While most icons are 24x24, there are many icons with weird sizes, such as `width="40.964" height="31.768" viewBox="0 0 196 152"`. Is that a bug or intended?
2. License is not truly open source, it prevents commercial use. I haven't seen a modern icon set that would restrict commercial use. Why did you choose that license?

**Comment by elax46** [comment]
they are the first icons that were added when the project was still immature then I improved it thanks also to the help of @rchiileea who takes care of creating the icons

As for the license, it is a choice as this is a non-profit project managed by me and @rchiileea and I don't think it's right that the icons can be used for commercial purposes unless the source is requested and cited

**Comment by cyberalien** [comment]
Thanks!

Added. It will appear in icon sets tomorrow when update script runs.

**Comment by elax46** [comment]
> Thanks!
> 
> Added. It will appear in icon sets tomorrow when update script runs.

Can I insert a new paragraph in the project readme to inform that the icons are also available on iconify?

**Comment by cyberalien** [comment]
That would be nice. Thanks!

Icons are available with `cbi` prefix, as requested. Packages that rely on API will have to wait util tomorrow, packages that rely on NPM (such as UnoCSS, Unplugin Icons, Iconify for Tailwind CSS) can already use it.

**Comment by elax46** [comment]
> That would be nice. Thanks!
> 
> Icons are available with `cbi` prefix, as requested. Packages that rely on API will have to wait util tomorrow, packages that rely on NPM (such as UnoCSS, Unplugin Icons, Iconify for Tailwind CSS) can already use it.

OK, I'll wait until the icons also appear on the website so I can insert all the references for use

**Comment by cyberalien** [comment]
It is up:

https://icon-sets.iconify.design/cbi/

Also at https://preview.iconify.design/cbi/ (preview of new version of website)

**Comment by rchiileea** [comment]
nice :) to se the icons some other place such as this project
