### ISSUE TITLE
Add Iconoir categories from their repo

### ISSUE THREAD

**Issue by binaryfire** [iconify/icon-sets#107]
Hi guys. Thanks for the great project!

I've discovered that Iconoir have metadata available for their icons in this file: [https://github.com/iconoir-icons/iconoir/blob/main/iconoir.com/icons.csv](https://github.com/iconoir-icons/iconoir/blob/main/iconoir.com/icons.csv).

Would it be possible to add that to your build process so it's included in `iconoir.json`?

**Comment by cyberalien** [comment]
Added. Thanks for reporting.

**Comment by binaryfire** [comment]
@cyberalien That was fast! Thanks 😊
