### ISSUE TITLE
Add Feather icons by colebemis

### ISSUE THREAD

**Issue by WilkerLopes** [iconify/icon-sets#110]
Hi,

I'd like to see the Feather icons [made by @colebemis](https://twitter.com/colebemis) at iconify :)

- Repository: [https://github.com/feathericons/feather/](https://github.com/feathericons/feather/)
- Website: [https://feathericons.com/](https://feathericons.com/)
- Licence : [MIT](https://github.com/feathericons/feather/blob/main/LICENSE)
- Grid Icon: 24px

**Comment by cyberalien** [comment]
It is available as Lucide, which is a fork of Feather icons: https://icon-sets.iconify.design/lucide/

Feather icons have been abandoned for several years, so several developers forked it and kept it maintained as Lucide Icons.

**Comment by WilkerLopes** [comment]
Thank you for the explanation

**Comment by WilkerLopes** [comment]
@cyberalien , I was comparing the two libs, and the icons are different:
Icons of eye in feather: [https://feathericons.com/?query=eye](https://feathericons.com/?query=eye)
Icons of eye in lucide: [https://icon-sets.iconify.design/lucide/?query=eye](https://icon-sets.iconify.design/lucide/?query=eye)

![image](https://github.com/iconify/icon-sets/assets/48459835/63cb9d5e-4255-4615-905d-629391a2e46c)
![image](https://github.com/iconify/icon-sets/assets/48459835/97640a40-367b-476b-ac6d-ebfba98e08ee)

**Comment by cyberalien** [comment]
It is the same.

On your first screenshot last icon is "target", which is also available in Lucide.

On second screenshot last icon is "scan-eye", which does not exist in Feather.

**Comment by WilkerLopes** [comment]
Yes, it was my error in the search, sorry

Em sex., 23 de fev. de 2024 10:31, Vjacheslav Trushkin <
***@***.***> escreveu:
