### ISSUE TITLE
Can't install @iconify-icons/f7 -- 404

### ISSUE THREAD

**Issue by theseamusjames** [iconify/icon-sets#111]
I may be misunderstanding how this works, but I'm trying this command: 

`npm install --save-dev "@iconify-icons/f7"`

According to [the documentation](https://iconify.design/docs/icons/icons.html) :

> There are 2 versions of packages available on NPM:
> 
> @iconify-icons/{prefix} that contains data as ES modules for modern development.  

I see the `f7.json` file listed in the `icon-sets` repo -- is that not the correct prefix?

**Comment by cyberalien** [comment]
Those packages are deprecated. See notice in documentation.

**Comment by theseamusjames** [comment]
@cyberalien Ah, wasn't clear to me that this was a split icon package. Thanks, this can be closed.
