### ISSUE TITLE
`@iconify/collections` does not provide a LICENSE

### ISSUE THREAD

**Issue by dargmuesli** [iconify/icon-sets#112]
I'm not sure if this is the source repo for https://www.npmjs.com/package/@iconify/collections, but `@iconify/collections` does not provide a LICENSE it appears. Providing a LICENSE would clarify legal questions of usage. It would be great if a license could be shipped with that package, thank you! :pray:

**Comment by cyberalien** [comment]
Added `license` field to `package.json`, clearly stating that license is MIT.
