### ISSUE TITLE
Add Kenney's Input Prompts

### ISSUE THREAD

**Issue by jf908** [iconify/icon-sets#113]
Website: https://kenney.nl/assets/input-prompts
Author: Kenney https://kenney.nl/
License: CC0
Icon Size: 64x64

Repo: https://github.com/jf908/Kenney-Input-Prompts
SVGs: https://github.com/jf908/Kenney-Input-Prompts/tree/main/svg
Suggested name: `kenney-input`

Although the icons are not my own, I'm committed to keeping the repo up to date (I have automated this process) and I have Kenney's permission to submit them. Let me know if there's anything I can do to help format-wise!

**Comment by cyberalien** [comment]
I don't understand color scheme of icons. Is it supposed to be black/white only?

Most icons I see are white, but then there are icons like this:

- Black and white and for some reason lots of empty space: https://github.com/jf908/Kenney-Input-Prompts/blob/main/svg/controller_icon_battery_half.svg 
- Another icon with huge empty space: https://github.com/jf908/Kenney-Input-Prompts/blob/main/svg/flair_number_7.svg
- Black and white with opacity: https://github.com/jf908/Kenney-Input-Prompts/blob/main/svg/flair_circle_3.svg

**Comment by jf908** [comment]
There are multiple colours used, the previews on the website make this more clear. It’s primarily white, but red for highlights, black for outlines, and some buttons have unique colours.

The icons in the flairs and overlay category are smaller and have black outlines because they are intended to be overlayed on top of other controller icons.

**Comment by cyberalien** [comment]
In its current state that icon set has no real use cases. White icons means it works only on dark backgrounds, icons mixed with black means it requires black or close to black background. Icons themselves have no use for web developers, only niche use for maybe some console related websites that would want to emulate keyboards.

If icons have no users that would find those icons useful, they have no place in Iconify.

The only way it can be added to icon sets is with modifications: only white icons with white changed to `currentColor`. That would remove black background and white text limitation. It would still be rather niche use case, but at least without color restriction, so maybe someone will find those icons useful. If this is acceptable, icon set can be added.

**Comment by jf908** [comment]
Understood, I was not aware that the multi colour icon sets could not be easily recoloured. I think having just white icons would be great.

I see that it’s quite straightforward to use iconify/util to filter and change colours, shall I do this on my repo or will you do it on your end?

Thank you, I know this set is quite niche but I look forward to using it in my upcoming web games and gameplay tutorials.

**Comment by cyberalien** [comment]
Changing colors can be done automatically during import, it is very easy to configure, so that's not a problem. Just need to confirm that you are ok with that because it will result in slightly different icons.

**Comment by jf908** [comment]
That will be ok, yes.

**Comment by cyberalien** [comment]
Sorry, after a bit more consideration decided not to add this set.

Reason is too many unusable icons. While icons with multiple colors can be easily filtered, icons that use only small part of viewBox, making them useless, cannot.

Icon set is too niche. Converting it to icon set usable for others cannot be fully automated so it is not feasible.
