### ISSUE TITLE
Adding new Icon set

### ISSUE THREAD

**Issue by daniyalAli29** [iconify/icon-sets#115]
Hi, 
I want to add my website's icon set to iconify. It is a complete set of icons in 2 colors (black , blue). 
I want to use iconify to manage my icons on my sanity studio. The icons are self designed in figma. I also have the svg files. Please let me know how can I add the icons to iconify and host them so that I and other devs can use the icons.
Figma file: https://www.figma.com/file/c7xb3jWqC4hJTXvfBJGxVE/Marketeq-Brand-Icon-Set?type=design&t=ieEydNumwRVGm8s3-6
Thanks

**Comment by cyberalien** [comment]
At quick glance that set looks good. It can probably be added.

To add it, I need to following information:
- License. It must have an open source license.
- Icon set name ("Marketeq Brand" ?)
- Preferred icon set prefix (`marketeq`?)

**Comment by eshmalf** [comment]
Icon set name ("Marketeq Brand" ?) : NO, It can be only "Marketeq"
Preferred icon set prefix (marketeq?) : YES.
Can you please explain how can I specify licence, as these icons are self designed in figma.

**Comment by daniyalAli29** [comment]
Icon set name ("Marketeq Brand" ?) : NO, It can be only "Marketeq"
Preferred icon set prefix (marketeq?) : YES.
Can you please explain how can I specify licence, as these icons are self designed in figma.

**Comment by daniyalAli29** [comment]
Really looking forward for a reply and addition of these icons. Please let me know about it.

**Comment by cyberalien** [comment]
Just post license name here, such as `MIT` or `Apache 2.0`

**Comment by daniyalAli29** [comment]
License: MIT
Icon set name: Marketeq
Preferred icon set prefix: marketeq
Figma file: https://www.figma.com/file/c7xb3jWqC4hJTXvfBJGxVE/Marketeq-Brand-Icon-Set?type=design&t=ieEydNumwRVGm8s3-6

**Comment by cyberalien** [comment]
Thanks. That's enough to add icon set, however it might take a while. For last 2 days I've been out of bed only few times to check email - got severe case if food poisoning, my brain doesn't work well enough to do anything.
