### ISSUE TITLE
`collection.total` count incorrect?

### ISSUE THREAD

**Issue by kaitoukid-1412** [iconify/icon-sets#116]
> Example pick: `Ant Design Icons`

![image](https://github.com/iconify/icon-sets/assets/15698245/ddffa549-e5f6-4801-978d-1f40259ecef1)
![image](https://github.com/iconify/icon-sets/assets/15698245/d565478f-815b-48cc-8efd-00e0ab446d39)
![image](https://github.com/iconify/icon-sets/assets/15698245/3352242b-500b-49cd-895c-90ac0b87bb44)
![image](https://github.com/iconify/icon-sets/assets/15698245/3d41b920-9af8-4834-95c5-d38c377f54f3)

```json
"dependencies": {
    "@iconify/json": "^2.2.200",
  }
```

> Please consider updating the `collections.json` file

**Comment by cyberalien** [comment]
It is correct. Total does not count duplicate icons (icons that have multiple names) and hidden icons (icons that were removed - they are still in icon set file to avoid breaking stuff for users who use them, but marked as hidden).
