### ISSUE TITLE
Adding owner icon set

### ISSUE THREAD

**Issue by elax46** [iconify/icon-sets#117]
Hi, besides me, could you also add @rchiileea as creator/co-owner of the [icon set](https://github.com/elax46/custom-brand-icons/), thanks

**Comment by cyberalien** [comment]
Sure. What text do you prefer?

**Comment by elax46** [comment]
I'll let @rchiileea choose how he prefers to write

**Comment by rchiileea** [comment]
rchiileea is fine :)

**Comment by elax46** [comment]
Then you can add Emanuele & rchiileea

**Comment by cyberalien** [comment]
Changed
