### ISSUE TITLE
Add Garrux Ascii ICONS

### ISSUE THREAD

**Issue by Garruxx** [iconify/icon-sets#118]
# Add Garrux-ascii Icons library 
I have created a library of icons and I would really love to make it part of iconify, it is under the MIT license and the suffix would be "garrux-ascii".

The icons were created by hand. I was motivated to create this library because I couldn't find icons in ascii art style. Please add it 🙏🏻

Github repository: [Github]( https://github.com/Garruxx/ascii-icons )
LICENCE: **MIT**

**Comment by cyberalien** [comment]
Sorry, no.

Those images are illustrations, not icons. They work only as large images. On small resolution, such as 24x24, which is commonly used for icons, all those details are not visible.

**Comment by Garruxx** [comment]
You are right, thanks for the feedback, I will try to make another version with better icons, to have a good representation in 24x24.👋🏻
