### ISSUE TITLE
Hi, is it possible to add `Cool Shapes 1.0.0 (MIT)`

### ISSUE THREAD

**Issue by kaitoukid-1412** [iconify/icon-sets#119]
![image](https://github.com/iconify/icon-sets/assets/15698245/039bc913-2341-46bd-9e99-81c536494bfa)

Website
```
https://coolshap.es/
```

Figma
```
https://www.figma.com/community/file/1367467631420622345
```

Direct download link
```
https://s.vjy.me/coolshapes
```

**Comment by cyberalien** [comment]
Sorry, no.

That set is not usable. While abstract shapes might have some use as icons, hardcoded colors with gradients make it completely useless.
