### ISSUE TITLE
Add Indiana University - Rivet Icons and Rivet Stickers

### ISSUE THREAD

**Issue by jameswilson** [iconify/icon-sets#121]
I'd like to see https://github.com/indiana-university/rivet-icons and https://github.com/indiana-university/rivet-stickers added to iconify.  The SVGs are high-quality and mostly already setup to iconify's specifications (I think).  

I'm new to Iconify and have tried to read through the docs which are very thorough, but I'm having trouble kind of figuring out where to start, and could use a bit of orientation.

The Rivet Icons collection are a monotone set. Explore them here: https://rivet.iu.edu/icons-stickers/icon-library/

Rivet Stickers on the other hand have a hard-coded duo-tone color palette of black (`#000`) for foreground paths and white (`#fff`) for solid fills in certain places. This is setup with the intention that both colors could be overridden, in theory, but in practice the most common thing would be to soften the hard `#000` foreground color to match `currentColor` of website font, leave the solid white fill color alone, and then display the SVG on top of a `<div>` (or style the `<svg>` itself to have a third circular background color -- not part of the SVG itself), selected from the Rivet Design System [color palette](https://rivet.iu.edu/utilities/color/) as depicted in the following screenshot from the [Rivet Design Kit documentation](https://rivet.iu.edu/getting-started/rivet-design-kit/#icons-and-stickers).

![design-kit-stickers-and-icons-2](https://github.com/iconify/icon-sets/assets/243532/5c3337dc-eb90-4395-a4c0-8129f632a56c)

* Based on your experience maintaining Iconify, will Rivet Stickers be possible to work with?

* When creating the JSON file for these sets, is there tooling that does all the work for you, or do  parts of the JSON file require hand editing?

**Comment by cyberalien** [comment]
Added icons.

Stickers aren't usable.
