### ISSUE TITLE
WeUI Icons

### ISSUE THREAD

**Issue by YunYouJun** [iconify/icon-sets#122]
- Repo: [weui/weui-icon](https://github.com/weui/weui-icon)
  - assets in [src/assets](https://github.com/weui/weui-icon/tree/master/src/assets)
  - If you need svg with suffix, see [YunYouJun/weui-icon/tree/master/packages/svg](https://github.com/YunYouJun/weui-icon/tree/master/packages/svg).
- Prefix: weui-
- License: MIT

**Comment by cyberalien** [comment]
Added.

It will be available in few hours.
