### ISSUE TITLE
Icons for Creative Commons licenses?

### ISSUE THREAD

**Issue by tamaracha** [iconify/icon-sets#125]
Would it make sense to have the CC icons as an icon set? Unfortunately, I cannot find a dedicated repo for their icons, but they're included in their [Chooser] repo. Maybe I could create a cleaner repo from the icons on their [download page] …

[chooser]: https://github.com/creativecommons/chooser
[download page]: https://creativecommons.org/mission/downloads/

**Comment by cyberalien** [comment]
Sorry, no. That set is not usable because of license.
