### ISSUE TITLE
The Brazilian Ministry of Culture

### ISSUE THREAD

**Issue by fernandolordao** [iconify/icon-sets#126]
I want to propose the inclusion of this beginning gallery to Iconify.
* Source URL: https://github.com/culturagovbr/icones
* Suggested Prefix: minc
* License: MIT

Will Iconify be recurrently loading new icons as they are published in the future?

**Comment by cyberalien** [comment]
No, sorry. This has no place in Iconify icon sets because it is useless to pretty much all users.
