### ISSUE TITLE
Icon set suggestions

### ISSUE THREAD

**Issue by zcraber** [iconify/icon-sets#129]
1. [duo-icons](https://github.com/fazdiu/duo-icons)
2. [web3icons](https://github.com/0xa3k5/web3icons)
3. [cryptocurrency-icons](https://github.com/spothq/cryptocurrency-icons)
4. [IconPark](https://github.com/bytedance/IconPark)
5. [picon](https://github.com/yne/picon)
6. [awsicons](https://github.com/boyney123/awsicons)
7. [MingCute](https://github.com/Richard9394/MingCute)

**Comment by zcraber** [comment]
Sorry, didn't intend to spam here. I searched your icon sets website before opening this issue, but these sets didn't show up due to one of the license filters I unknowingly selected, my bad! 

Now, I searched again to find that IconPark, Cryptocurrency Icons and MingCute are already included. 

I've updated the suggestions if you still want to look at other suggestions.

**Comment by cyberalien** [comment]
Added duo-icons, the rest are either already added or not usable.
