### ISSUE TITLE
Guam flag is missing

### ISSUE THREAD

**Issue by tfoxkiu** [iconify/icon-sets#132]
Hi! I noticed that the Guam flag is present in https://github.com/lipis/flag-icons/blob/4390ff1d78e8bc2706305eaaec861ff26afdc8c1/country.json#L889-L897 , but for some reason it's not included in https://github.com/iconify/icon-sets/blob/d011f7018304ca8c1adc9f2616105a98ffedae4b/json/flag.json

Not sure how that file is generated so I don't know why that specific flag is missing. Hopefully someone with more knowledge knows something about this.

**Comment by cyberalien** [comment]
That's not a bug. SVG for that flag contains text elements. Icons that contain text are rendered differently on different operating systems and even in different browsers, so icons with text elements are not allowed.

It is a common issue with various icon sets that contain flags, which often contain icons that require on various fonts, sometimes even weird country specific fonts.

**Comment by tfoxkiu** [comment]
Thanks for the fast response! I realized you created https://github.com/lipis/flag-icons/issues/539 where https://github.com/lipis/flag-icons/pull/967 is supposed to fix this, but `gs` still has text elements (while in `sm` were removed). I'm going to create an issue in https://github.com/lipis/flag-icons and see if there can be a solution.

**Comment by tfoxkiu** [comment]
Wanted to comment that the `gu` flag is now present starting from `@iconify-json/flag@1.2.1`. Thanks for the help!
