### ISSUE TITLE
Add Papirus

### ISSUE THREAD

**Issue by hexahigh** [iconify/icon-sets#138]
Hello, i really like Iconify and how simple it is to use. I would love to see the Papirus icon theme added to the official icon-sets as it is very clean and has icons for alot of applications.
[Here is a link to the repo](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme)

**Comment by cyberalien** [comment]
Sorry, I won't be adding any GPL licensed sets to Iconify.

That license can no longer be considered open source due to US laws (see Linux Foundation recent drama).
