### ISSUE TITLE
Add NRK core-icons & YR weather symbols

### ISSUE THREAD

**Issue by hexahigh** [iconify/icon-sets#139]
## NRK core icons
**Site:** https://static.nrk.no/core-icons/latest/index.html
**Repo:** https://github.com/nrkno/core-icons
**License:** Icons & logos prefixed with `nrk-logo-` or `nrk-super-` are under a special license which requires attribution, everything else is under `CC-BY-4.0`
**Notes:** Icons can be found in the `lib/logo` `lib/icon` `lib/preview` and `lib/expressive` directories

## YR weather symbols
**Site:** https://nrkno.github.io/yr-weather-symbols/
**Repo:** https://github.com/nrkno/yr-weather-symbols
**License:** Attribution required, commercial use allowed.
**Notes:** Icons can be found in the `symbols` directory.
There are 3 variants, perhaps append/prepend a type? for example `rainshowers-night-dark`, `rainshowers-night-light` and `rainshowers-night-shadow`

Thank you for taking the time to review my request, i really appreciate the work that you do!

**Comment by cyberalien** [comment]
Partially added NRK: added only `lib/icon` icons. Logos have unusable license, other directories you've listed are empty.

**Comment by hexahigh** [comment]
Thanks for adding them! Why were you unable to add the YR weather symbols? I thought the license was ok.

**Comment by cyberalien** [comment]
Those are high detailed images, not icons. They do not fit this repository.

**Comment by hexahigh** [comment]
Oh alright, I should probably close this issue then. :)

**Comment by cyberalien** [comment]
I kept it open because I do plan to add illustrations at some point :)

But it probably will take some time.
