### ISSUE TITLE
Add Solid Variant to MynaUI Icon Set

### ISSUE THREAD

**Issue by praveenjuge** [iconify/icon-sets#140]
Hey, 

I am the creator of MynaUI Icons: https://icon-sets.iconify.design/mynaui/

I have recently added a solid variant to MynaUI Icons: https://mynaui.com/icons?mode=solid

You can see all the solid icons in a separate folder called `icons-solid`: https://github.com/praveenjuge/mynaui-icons/tree/main/icons-solid

It will be great if we can add this version to iconify too! Let me know if you need any changes from my side!

**Comment by cyberalien** [comment]
Thanks for creating awesome set!

To avoid naming conflicts, solid icons should have different names. Would it be ok to add `-solid` suffix (it will be added by import script automatically, you don't need to change anything) to solid icons or do you prefer to handle them differently?

**Comment by praveenjuge** [comment]
@cyberalien that suffix sounds perfect!

**Comment by cyberalien** [comment]
Done.

New icons will appear after next update (last update was earlier today, next one is on Wednesday)
