### ISSUE TITLE
lsicon Icon Set Information Update Request

### ISSUE THREAD

**Issue by FaureWu** [iconify/icon-sets#146]
I am one of the authors of the lsicon library. Due to our previous negligence, the warehouse information recorded at `icon-sets` is incorrect. It should have been provided by the wis design team, but only my name was recorded. At the same time, I also hope to update the website's url to [www.lsicon.com](http://www.lsicon.com/) to replace the figma address.

But I don't know how to operate. Can I seek some help?

**Comment by cyberalien** [comment]
I'll change it.

Author: Wis Design
Website: https://www.lsicon.com/

Would that be correct?

**Comment by FaureWu** [comment]
@cyberalien No problem. Thank you very much.

**Comment by cyberalien** [comment]
Changed. Updated info will appear after tomorrow's icon sets update.

Thanks for creating an excellent icon set!
