### ISSUE TITLE
Dark Mode Missing

### ISSUE THREAD

**Issue by wh1337** [iconify/icon-sets#151]
After a recent update, dark mode is no longer available on the Icon Sets website.

**Comment by cyberalien** [comment]
That's intentional. Code is there but it is disabled for now.

**Comment by cyberalien** [comment]
Enabled it on website. Button to toggle dark mode is in footer.

Dark mode is also detected from preferences, so if you have preferences set to dark, it should show dark mode without needing to toggle it.
