### ISSUE TITLE
Jetbrains icons set.

### ISSUE THREAD

**Issue by 4l1fe** [iconify/icon-sets#22]
Hey, what do you think about including this set https://jetbrains.design/intellij/resources/icons_list/?

**Comment by cyberalien** [comment]
I don't see any mentions of license.

There is also no link to Git repository or NPM package to download (or any other version control system or package manager that would allow automatic updates).

**Comment by 4l1fe** [comment]
Short research brought me to here https://github.com/JetBrains/icons. But it isn't that set...

If i'll ask Jetbrains and get an answer of how we can get a license and a maintainable icons set i write it to this issue.

**Comment by Jogai** [comment]
Here is a set that looks like it: https://github.com/JetBrains/icons
