### ISSUE TITLE
Add Iconsax

### ISSUE THREAD

**Issue by X7md** [iconify/icon-sets#23]
## Request add new icon package.
 
iconsax the official icons of the [Vuesax](https://vuesax.com/) framework.

[Iconsax WebSite](https://github.com/lusaxweb/iconsax)

[GitHub Repo](https://github.com/lusaxweb/iconsax)

### License
https://iconsax.io/#license

![image](https://user-images.githubusercontent.com/54203033/141686650-e6c8834b-c1bb-4172-baef-0810512776d0.png)

**Comment by cyberalien** [comment]
It has been over a year, no response from author about license and icons weren't updated since then either. I guess that icon set can be considered to be unmaintained. That's unfortunate, icons were really nice.
