### ISSUE TITLE
Update rhythm 

### ISSUE THREAD

**Issue by bennetfabian** [iconify/icon-sets#29]
What's the update rhythm atm?
Back when we discussed this in #25 it was three times a week.

Unfortunately there are some inconsistencies that may want to be changed.
In the README it says frequently but the repo's description on the right side says daily.

Maybe it should be communicated more consistent.
Thanks in advance @cyberalien

**Comment by cyberalien** [comment]
When that issue was discussed, this repo had 2 branches: `master` for version 1 and `next` for upcoming version. Since then old branch has been archived and `next` replaced it.

Forgot to fix text in former `next` branch.

**Comment by cyberalien** [comment]
Fixed. Thanks for reporting!
