### ISSUE TITLE
Add Country Flag Icons

### ISSUE THREAD

**Issue by vhscom** [iconify/icon-sets#30]
Surprised these aren't in here yet. :smile: https://flagicons.lipis.dev/

**Comment by cyberalien** [comment]
There was a problem with that icon set a while ago: several icons relied on fonts, making them unusable and icon set was not actively maintained. See https://github.com/lipis/flag-icons/issues/539

However looks like it is maintained now. Will test it.

**Comment by cyberalien** [comment]
Checked it again. Flags `gu` and `sm` still require fonts, so those 2 flags are unusable.

I think I'll add it without those icons.

**Comment by cyberalien** [comment]
Added.

It will take a while to appear. I'm in process of rewriting script that updates icon sets, this icon set was added to new version, not old version, so icon set will appear only when new script will be fully ready, which should be sometime next week.

Two flags mentioned above will be missing from icon set.

**Comment by vhscom** [comment]
Awesome. Thanks @cyberalien. Hope the scripting goes well.

**Comment by vhscom** [comment]
Opened two more issues in the flag icons package to get the other flags cleaned up and linked them to https://github.com/lipis/flag-icons/issues/539. With any luck they'll be finished before the update script is done and can be included with the rest of the flags.

**Comment by cyberalien** [comment]
Thanks.

> With any luck they'll be finished before the update script is done and can be included with the rest of the flags.

It doesn't matter when those icons will be added. Those icons aren't blacklisted, script just checks for font tags inside SVG and ignores icons that contain it. Icon sets are updated several times a week (and I want to change it to faster updates for individual sets within minutes of update being pushed by author to source repository), so it will be automatically added later.

**Comment by vhscom** [comment]
Solid. :muscle:

**Comment by vhscom** [comment]
Fantastic, thanks @cyberalien. :heart:
