### ISSUE TITLE
Adding OOUI icons

### ISSUE THREAD

**Issue by twilight1794** [iconify/icon-sets#31]
Hi. I would like to use [OOUI icons](https://doc.wikimedia.org/oojs-ui/master/demos/?page=icons&theme=wikimediaui&direction=ltr&platform=desktop) on Iconify. They are used mainly on Wikimedia wikis.

Thanks.

**Comment by cyberalien** [comment]
Added.

It will take a while to appear. I'm in process of rewriting script that updates icon sets, this icon set was added to new version, not old version, so icon set will appear only when new script will be fully ready, which should be sometime next week.

**Comment by cyberalien** [comment]
New update script is finally ready, so icon set is available in API, various NPM packages and Packagist package.
