### ISSUE TITLE
academicons

### ISSUE THREAD

**Issue by haoyun** [iconify/icon-sets#32]
I'd like to suggest the integration of [Academicons](https://jpswalsh.github.io/academicons/). It provides some unique icons that are not available in other font sets.

> The Academicons font is licensed under the SIL OFL 1.

SVGs are available:
https://github.com/jpswalsh/academicons/tree/master/svg

**Comment by cyberalien** [comment]
Added.

It will take a while to appear. I'm in process of rewriting script that updates icon sets, this icon set was added to new version, not old version, so icon set will appear only when new script will be fully ready, which should be sometime this week.
