### ISSUE TITLE
Would be great if we could add Flagpack, by @Yummygum.

### ISSUE THREAD

**Issue by didier** [iconify/icon-sets#33]
![Flagpack Cover Image](https://camo.githubusercontent.com/4797b8e4283dd9b7f133c25cd7c487784098f5f710a917fbfcb99b3568879e21/68747470733a2f2f666c61677061636b2e78797a2f6d6574612d696d6167652e706e67)

As the title implies, this would make a super diverse and helpful flag collection available for the greater public. This can be especially useful when using `unplugin-icons`, so they're available in all bundlers and environments.

https://github.com/Yummygum/flagpack-core

**Comment by cyberalien** [comment]
Added.

It will take a while to appear. I'm in process of rewriting script that updates icon sets, this icon set was added to new version, not old version, so icon set will appear only when new script will be fully ready, which should be sometime this week.

**Comment by didier** [comment]
@cyberalien how are they added? Because I'm not sure they were iconify-ready per say. Either way, very cool. Thanks for the swift response.

**Comment by cyberalien** [comment]
Icon sets are generated by script, which does the following:
- Retrieves data from source (GitHub, NPM, Figma).
- Parses icons: validates them, fixes palette when needed (so icons with palette do not rely on default colours, icons without palette rely on `currentColor`), optimises.
- Generates packages and publishes them.

All functions used by script are available in Iconify Tools package: https://github.com/iconify/tools

**Comment by cyberalien** [comment]
New update script is finally ready, so icon set is available in API, various NPM packages and Packagist package.
