### ISSUE TITLE
Fluent 16x16 Icons Sized Incorrectly

### ISSUE THREAD

**Issue by alexdobson** [iconify/icon-sets#35]
It appears that all 16x16 fluent icons on Iconify [(here)](https://icon-sets.iconify.design/fluent/) have been sized and offset incorrectly - they are no longer centered like all other icons, and are also contained with 20x20 bounding box.

Here's an example of one 16x16 icon: 

<img width="182" alt="Screenshot 2022-02-15 at 16 12 34" src="https://user-images.githubusercontent.com/67032270/154102503-e512b92c-670d-4898-99f7-b468eadfbde4.png">

Notice how the icon is contained within a 20x20 box, instead of a 16x16 one, and is also off-centre.

**Comment by cyberalien** [comment]
Confirmed. Thanks a lot for reporting!

**Comment by cyberalien** [comment]
Fixed.

All packages of affected icon sets have been updated, website will take a while to update because it is hosted on GitHub Pages, which takes about an hour to rebuild large website.
