### ISSUE TITLE
Different Feather Icon sets

### ISSUE THREAD

**Issue by peterbuk** [iconify/icon-sets#37]
Hello, I just realized today that one of my favourite icon sets, Feather, is actually linked to an entirely different set under Iconify. 

It turns out there is a "**Feather Icon**" set (which is what is currently used in Iconify), and a "**Feather Icons**" set.

Feather Icon: https://github.com/feathericon/feathericon

Feather Icons: https://github.com/feathericons/feather

The second set is much more popular (based off of stats on github, and it's the first result on google). I think a lot of people may be using "Feather" through Iconify without realizing they are using the wrong set. 

Can we get this second set added?

Thanks!

**Comment by cyberalien** [comment]
It is available as `Lucide`: https://icon-sets.iconify.design/lucide/

Even though Feather Icons set has lots of stars, it is actually abandoned, but Lucide is a fork that is being developed.
