### ISSUE TITLE
Wrong license name for Octicons... maybe?

### ISSUE THREAD

**Issue by Andre601** [iconify/icon-sets#40]
Not really sure about this, but the Iconify site lists the GitHub Octicons as licensed under "Open Font License".

This could just be me not quite understanding things, but the actual license used by GitHub for Octicons is the MIT license. Could perhaps be that the license changed after you added them to the list, but if that is indeed wrong should the license be updated to reflect this.

But again, this could also be me not quite understanding Licenses in combination with Fonts/SVGs, so...

**Comment by cyberalien** [comment]
Thanks for noticing and reporting!

Not sure where OFL came from, there is currently no mention of it anywhere in readme. Most likely it used to be OFL for icons, MIT for code, but then OFL got dropped.

It will be fixed in tomorrow's update.
