### ISSUE TITLE
Font Awesome Solid (v6): sun-bright is missing

### ISSUE THREAD

**Issue by Pukimaa** [iconify/icon-sets#42]
`sun-bright` that got added in FontAwesome 6 is missing in the newest Font Awesome Pack (says its FontAwesome 6.1.1).

Here the source: https://fontawesome.com/icons/sun-bright?s=solid
And the Pack: https://icon-sets.iconify.design/fa6-solid/

**Comment by cyberalien** [comment]
That's a FontAwesome Pro icon, it is not part of open source package.
