### ISSUE TITLE
Add Devicons set

### ISSUE THREAD

**Issue by vhscom** [iconify/icon-sets#43]
Hopefully this one is better than my flub in #38.

https://github.com/vorillaz/devicons
https://icalvin102.github.io/svelte-nerdfonts/

Contains icons for developers. Part of what gets sucked in to Nerd Fonts.

**Comment by cyberalien** [comment]
Sorry, even though this icon set is little bit better than ForkAwesome, it is still bad. Icons are just scaled down logos placed in 32x32 grid with seemingly random padding around icon, not even aligned to grid.

It is a very small set of icons, maintenance stopped 7 years ago. Technology moves fast, what was relevant back then is irrelevant today. No point in adding icons for outdated technologies.

Every icon in that icon set is available in one of maintained icon sets: Logos, BoxIcons, VSCode Icons, Codicons and probably more.

**Comment by cyberalien** [comment]
Google have good article on material design website, it shows how to design icons correctly: https://material.io/design/iconography/system-icons.html#design-principles

It might help you understand how to spot good icon set.

Some of that information is specific to material design, but most of it applies to all icon sets. More and more modern icon sets follow that or similar guides. Most important parts are grid system with padding to make different icons fit well together, following pixel grid (not just placing shapes wherever).

How to test it while looking at icons? Easiest way is to paste icon code to Figma. It is free and easy to use. In Figma you can zoom in icon, check shapes to make sure they do follow some grid.
