### ISSUE TITLE
HeroIcons update issue

### ISSUE THREAD

**Issue by chasegiunta** [iconify/icon-sets#54]
HeroIcons recently released v2.0.0 of their icon package. 

Unfortunately, this update was major (changed the stroke width, the style of the icons, introduced a newer size, etc). In v1.0, the icon identifiers were prefixed as `heroicons-outline:icon` & `heroicons-solid:icon`... The prior remains untouched and still shows the v1.0 icons (for now, but looks like you removed `heroicons-outline`   https://github.com/iconify/icon-sets/commit/d5ebd94075f1fd65fdd6fadd358604d688ffa8bb, does this mean these icons will disappear??)

The latter was updated overnight to 2.0 and the change has surely by now propagated to hundreds of sites without warning.

Surely there has to be an upgrade path or something, not just removing and replacing entire icon sets?

**Comment by cyberalien** [comment]
This was indeed a major change. In old version `solid` was 20x20, `outline` was 24x24. In new version there are 3 types of icons:
- `solid` 20x20 (available as `heroicons-solid`)
- `outline` 24x24
- `solid` 24x24

That created a bit of mess. Also new outline version is different than old one.

So I've updated `heroicons` set instead. It now contains both 24x24 variations.

**Comment by chasegiunta** [comment]
> heroicons-solid contains updated 20x20 icons, which seem to be same as old ones (probably kept for legacy support)

Unfortunately, they are not, which is how I woke up to notice the change in our icon styles on our production sites.

So, your recommended solution is quickly go through every codebase that uses `heroicons-solid` and update it to `heroicons` and append `-solid` to the end of the name, and deploy as fast as we can?

I hope you understand why I'm asking that updates to iconsets now and in the future should not be done this way.

**Comment by cyberalien** [comment]
Doh.

I think this needs reversing to v1 for `heroicons-solid`. Not sure yet what to do with new 20x20 solid version...

**Comment by cyberalien** [comment]
Reversed `heroicons-solid`. It also includes new icons to avoid breaking things for users who started using icon set in last few days. For icons that exist in both v1 and v2, it uses v1.

Now need to figure out where to put v1 of 20x20 solid icons.

**Comment by chasegiunta** [comment]
I wonder if the move going forward with updates like this is the same as what you've done with Font Awesome, eg:

| HeroIcons 1.0  | HeroIcons 2.0 |
| ------------- | ------------- |
| `heroicons-outline:check`  | `hi2:check`  |
| `heroicons-solid:check`  | `hi2:check-outline`  |
|   | `hi2:check-mini`  |

**Comment by cyberalien** [comment]
Good idea and that's sort of how it is right now. `heroicons-outline` and `heroicons-solid` are both v1 and will remain as is, in "Archive / Unmaintained" category similar to FontAwesome 4/5.

**Comment by cyberalien** [comment]
Solved it. `heroicons` now contains all icons. 20x20 solid icons use suffix `-20-solid`. Also it supports possibility of 20x20 outline icons if they'll be added in future.

API should be updated in few minutes, website in about an hour.

Thanks a lot for reporting it!

**Comment by cyberalien** [comment]
Everything has been updated.

v2: https://icon-sets.iconify.design/heroicons/
v1 solid: https://icon-sets.iconify.design/heroicons-solid/
v1 outline: https://icon-sets.iconify.design/heroicons-outline/

**Comment by cyberalien** [comment]
Another minor bug caused by fix: v1 icon sets are currently marked as hidden. It doesn't affect their functionality, so all icons work as expected, only causes them to not show up in search results and when browsing icon sets.

It will be fixed on next update.
