### ISSUE TITLE
[Feature request] Add both with and height to the path

### ISSUE THREAD

**Issue by pavlyukpetr** [iconify/icon-sets#55]
Hello,
would be great to have with and height next to icon's body.
I am using your fa-solid.json and not all of the icons have width, but its necessary for svg viewBox.
Without it the icons look like this
![Снимок экрана 2022-08-28 в 01 00 39](https://user-images.githubusercontent.com/11602610/187050865-bd1f7a5f-4ce5-47bf-9bc6-fc346b28e0e2.png)

**Comment by cyberalien** [comment]
But it does have it. See "Default values" section of https://docs.iconify.design/types/iconify-json.html
