### ISSUE TITLE
Grab "optimized" Heroicons, rather than src

### ISSUE THREAD

**Issue by chasegiunta** [iconify/icon-sets#56]
This is a bit silly, and hopefully an easy fix, but it seems that Iconify may currently be grabbing icons from the heroicons `src` [folder](https://github.com/tailwindlabs/heroicons/tree/master/src) (or somewhere else) rather than the `optimized` [folder](https://github.com/tailwindlabs/heroicons/tree/master/optimized).

It looks like the _optimized_ icons have the `stroke-width` applied to `svg` rather than the internal `path`'s which allows for css manipulation via the `stroke-width` rule. It also sets `currentColor` on the svg, and removes the color attribute on the internal paths.

This is probably more complicated issue, but if possible, it would be ideal to use the optimized icons as to be able to customize the stroke width.

**Comment by cyberalien** [comment]
It won't make any difference because icon data in Iconify doesn't allow any attributes on SVG element. All attributes are moved to path, so result would be the same.

You can target shapes that use `stroke-width` with this:
```css
svg [stroke-width="2"] {
    stroke-width: 1.5px !important;
}
```

**Comment by chasegiunta** [comment]
Okay, sounds good. Thanks.
