### ISSUE TITLE
Add GitLab Pajamas Product Icons

### ISSUE THREAD

**Issue by jameschensmith** [iconify/icon-sets#57]
#### Summary

Requesting GitLab Pajamas product icons be added. Not sure if prefix should be `gitlab` or `pajamas` 🤔 

#### Details

- [Pajamas Design System by GitLab](https://design.gitlab.com/)
- [Figma file](https://www.figma.com/community/file/1051267829358377715)
- [Repository](https://gitlab.com/gitlab-org/gitlab-svgs) (icons should be located under `sprite_icons`)

**Comment by cyberalien** [comment]
Good open source icon set.

Added. Some icons were skipped though, which weren't 12x12 or 16x16: 2 illustrations that were put in `sprite_icons` by mistake and many status icons, most of which also use shapes with white fill.

**Comment by cyberalien** [comment]
Actually, they are not illustrations, but they aren't proper icons either. So I think they don't fit anywhere: `double-headed-arrow` and `dotted-circle`. First one is more like illustration, second one is just a weird icon. Possibly leftovers from old code.
