### ISSUE TITLE
Dashboard Icons

### ISSUE THREAD

**Issue by markus-li** [iconify/icon-sets#58]
There's [a set of icons](https://github.com/walkxcode/Dashboard-Icons) very useful in the world of Dashboards, such as [Homarr](https://github.com/ajnart/homarr).

The SVG icons in that repo would be great to have access to, but the licensing may be an issue, this is what it says in the LICENSE file:
```
(Almost) All product names, trademarks and registered trademarks in the images in this repository, are property of their respective owners. All images in this repository are used by the users of the Dashboard Icons project for identification purposes only.

The use of these names, trademarks and brands appearing in these image files, do not imply endorsement.
```

What do you think, would this be a suitable set to add?

**Comment by cyberalien** [comment]
Sorry, but that icon set is terrible. Icons don't follow any grid, they are more like illustrations. They have different styles, different padding.

Just look at few icons:
https://github.com/walkxcode/Dashboard-Icons/blob/main/svg/chromium.svg - icon with padding, which seems random
https://github.com/walkxcode/Dashboard-Icons/blob/main/svg/uptime-kuma.svg - massive padding on sides
https://github.com/walkxcode/Dashboard-Icons/blob/main/svg/traefik.svg - misaligned, padding on left side, part of image cut on right side
https://github.com/walkxcode/Dashboard-Icons/blob/main/svg/firefox-nightly.svg - doesn't even work
https://github.com/walkxcode/Dashboard-Icons/blob/main/svg/actual.svg - another mess that doesn't work
https://github.com/walkxcode/Dashboard-Icons/blob/main/svg/caddy.svg - no padding, different design style

and so on. Those are randomly picked examples. Looking at actual icon code, it seems to be designed as illustrations with floating numbers in viewBox, shapes placed randomly not following any logic.

**Comment by cyberalien** [comment]
Also they do not have valid open source license. License provided in repository clearly states that it applies only to documentation and code. So icon set cannot be added Iconify because only icon sets with valid open source licenses are allowed.

**Comment by markus-li** [comment]
I definitely see your point, thank you for the detailed answer. Being a developer who knows very little about creating icons, how would I most efficiently go about creating an icon set of that type which is not ill-formed? Writing code to do it would not be an issue. I live in code, just not in SVG and icons.

**Comment by markus-li** [comment]
Yes, thank you, that is a great intro to what to consider, I'll see how I can sort that out with these types of icons. Since the icons are for open source projects in most cases, it should be doable from a licensing point-of-view.
