### ISSUE TITLE
Add Game Icons

### ISSUE THREAD

**Issue by zAlweNy26** [iconify/icon-sets#59]
I think this would be a nice addition!
[Game Icons](https://github.com/game-icons/icons)

**Comment by cyberalien** [comment]
I'm not sure about that set. It does look ok, but there are issues:
- All icons have black rectangle. From quick inspection I think it can be removed to extract actual icon, so it might not be an issue. Need to test it on all icons.
- Icons have very high details, so they are more like illustrations than icons. Scaled down to 32x32 lines are barely visible on some images and they don't follow any guides.

Need to properly test it. So far it looks like maybe it might be usable.

**Comment by zAlweNy26** [comment]
Thank you for considering them! However, about the second point, I don't really agree, to me they look quite visible despite being a bit complex (and I'm using them at 24x24).

**Comment by averrin** [comment]
As I know, you can download a full set with white foreground and transparent background from the site. 
And yes, im really need it. Im using Iconify for my FoundryVTT modules and native GameIcons set will be a huge present for me.

**Comment by averrin** [comment]
Oh, I figured out how to create and use it locally as json-package.

**Comment by cyberalien** [comment]
Added, except for icons from `badges` directory.

This is a really unique icon set, has many icons that nobody else has.

**Comment by zAlweNy26** [comment]
> Added, except for icons from `badges` directory.
> 
> This is a really unique icon set, has many icons that nobody else has.

Can I ask you what's wrong with this directory?

**Comment by cyberalien** [comment]
> Anyway can I ask you what's wrong with this directory?

Badges are 2 color icons: one for circle, one for shape. Without circle icon is not usable, so one color cannot be removed.
