### ISSUE TITLE
Some Heroicons not displaying

### ISSUE THREAD

**Issue by RicoTrevisan** [iconify/icon-sets#62]
Hi, Long time user, first time caller. Thanks for all the work you've done with Iconify.

The new Heroicons was working fine until recently. Some of the icons are not loading via the API and sometimes not even on iconify.design. Here's a screenshot from earlier today when suddenly some `check` icons were not loading.

<img width="1141" alt="CleanShot 2022-10-15 at 13 00 57@2x" src="https://user-images.githubusercontent.com/2459327/195982955-10cd2148-fcf3-4559-9014-6f4e3cc01cda.png">

**Comment by cyberalien** [comment]
This is weird. Thanks a lot for reporting!

**Comment by cyberalien** [comment]
Fixed!

Issue was caused by misconfiguration on server in Frankfurt. Earlier today I was doing maintenance, accidentally messed up configuration on that server, so it was using very old file for `heroicons`. Other servers weren't affected.

It might require clearing browser cache to get rid of bug.

**Comment by RicoTrevisan** [comment]
It's working now, thanks!
