### ISSUE TITLE
Vector Logo Zone

### ISSUE THREAD

**Issue by markus-li** [iconify/icon-sets#65]
Would the below be a good fit to include in Iconify?

To me it seems like a clean collection of icons/logos, but I might be wrong.

https://github.com/VectorLogoZone/vectorlogozone/tree/main/www/logos

**Comment by cyberalien** [comment]
That looks like a collection of random images, not an icon set. 

It seems to have 2 types of icons:
- 120x60 with logo placed somewhere in middle and seemingly random padding on all sides of icon.
- 64x64 with logo just scaled to fit in it.

Doesn't look like any work was done to adjust icons, they were just collected from web and resized to fit 2 sizes.

Really bad quality. Unusable as icons.

**Comment by markus-li** [comment]
This is the best collection I've found of logos as icons, which is something I do find is lacking. But with your judgment of it passed I apologize for bringing subpar quality for you to look at.
Internally we've started on a small collection for what we use, I'll soon have it cleaned enough to push to a repo and I'll ask for your opinion on that instead. It's split between different licenses since it's all from PD via MIT to GPLv3...

**Comment by cyberalien** [comment]
Please do continue bringing up icon sets, they all should be looked at. :) 

But that icon set is not usable. If icons are used as is in their intended size, sure, it looks ok. But if they are scaled down to normal icon size, such as 24px, they look really bad.

Icon sets in Iconify are all meant to work as small icons. Larger images and illustrations are not intended use case.

**Comment by markus-li** [comment]
Now with tags being usable, maybe the target could be expanded for higher-detail icons intended for 48px/64px as smallest intended size and tag them with large or something such? There are plenty of cases where icons with more details could be very much usable, logos as icons being one such use-case. As a platform Iconify is far superior to anything else in similar scope, the collections made available are also good, but expanding into this use case area is something at least I would love to see.

**Comment by cyberalien** [comment]
That might be a good idea. However, I'm not convinced that using tags will solve it. It would still flood search results, but would require users to do extra work to filter results.

I think better approach would be to make a different set: set of illustrations. It would be separate set hosted on different API with its own search engine. Icon components already support multiple APIs using API providers (such as `@illustrations:prefix:name` instead of `prefix:name` in icon name).

Need a good bunch of vector illustration sets to start with though. Ideas are welcome!

**Comment by markus-li** [comment]
You may be right there, or make it possible to filter on size, with 24px being default and showing only icons meant for 16/24px, for example? The data is already in the sets.

As for vector illustrations, maybe the 64px versions in Vector Logo Zone could be a start? Or are they not good enough even for that?

**Comment by markus-li** [comment]
As for vector illustration sets I often use this list:
https://www.toools.design/free-open-source-illustrations

The problem is that some of the licenses used do not allow compiling collections and/or providing the illustrations in a service.

**Comment by Geeratipon** [comment]
The only

**Comment by cyberalien** [comment]
Closing this as not planned.
