### ISSUE TITLE
Feather Icon is missing icons

### ISSUE THREAD

**Issue by Snailedlt** [iconify/icon-sets#67]
The newest version of Feather icons has 287 icons, while the version used here has 255 icons. Would be nice if it could be updated to the newest version. 

Links:
https://feathericons.com/
https://icon-sets.iconify.design/fe/

I might be able to contribute with a PR, but would need some guidance since there's no `CONTRIBUTING.md` I can refer to

**Comment by cyberalien** [comment]
Thanks for noticing. Feather icons is marked as abandoned, so it wasn't automatically checked for updates. I'll run update script to include missing icons.

All those icons exist in Lucide, which is a fork of Feather icons and is actively maintained: https://icon-sets.iconify.design/lucide/

**Comment by cyberalien** [comment]
Actually... those are different icon sets. "fe" is Feather Icon, this is their website: https://github.com/feathericon/feathericon (though it is also abandoned)

Icon set you are looking for is "feather": https://icon-sets.iconify.design/feather/

**Comment by Snailedlt** [comment]
> Actually... those are different icon sets. "fe" is Feather Icon, this is their website: https://github.com/feathericon/feathericon (though it is also abandoned)
> 
> Icon set you are looking for is "feather": https://icon-sets.iconify.design/feather/

Ohh right! Thanks for the quick replies... I guess that solves this issue then! :D

**Comment by igorjacauna** [comment]
Hello! And about this: https://github.com/feathericons/feather

Is it a different project or a forked project?

**Comment by cyberalien** [comment]
> Hello! And about this: https://github.com/feathericons/feather
> 
> Is it a different project or a forked project?

That's original project that Lucide is based on.
