### ISSUE TITLE
Invalid license spdx in @iconify-json/mdi package.json

### ISSUE THREAD

**Issue by firecow** [iconify/icon-sets#69]
```
$ npx license-checker-rseidelsohn --development --summary --excludePrivatePackages --onlyAllow "${NPM_LICENSE_CHECKER_ONLY_ALLOW_DEVELOPMENT}" ${exclude_opt}
Package "@iconify-json/mdi@1.1.35" is licensed under "Custom: https://docs.iconify.design/types/iconify-json.html" which is not permitted by the --onlyAllow flag. Exiting.
```

It would be very very nice to know, what license this package is published under.

Edit: It would be nice, if it has a valid spdx license `Apache-2.0` instead of `Apache 2.0`

https://raw.githubusercontent.com/iconify/icon-sets/master/json/mdi.json It seems like the title is used instead of the spdx, somewhere in the publishing routine.

https://www.npmjs.com/package/@iconify-icons/brandico This one seems to be invalid as well.

I think many of the "packs" use invalid spdx in package.json

**Comment by cyberalien** [comment]
Thanks for reporting!

Bug confirmed and fixed in parser. I'm running update script to fix all packages, should be fixed soon.

**Comment by firecow** [comment]
That was fast 😁 Thanks man...
