### ISSUE TITLE
Cryptocurrency black and white

### ISSUE THREAD

**Issue by yangar** [iconify/icon-sets#70]
The crypto currency icons set is in black and white on Iconify:
http://icon-sets.iconify.design/cryptocurrency/

There is a colorized set on the original source:
https://github.com/spothq/cryptocurrency-icons/tree/master/svg/color

Might be better to use it with colors?

**Comment by cyberalien** [comment]
Added: http://icon-sets.iconify.design/cryptocurrency-color/
