### ISSUE TITLE
Update Material Design Icons and Material Design Icons Light attribution

### ISSUE THREAD

**Issue by mririgoyen** [iconify/icon-sets#71]
Hello, I'm a founding member of [Pictogrammers](https://pictogrammers.com/) and a core contributor to the [Material Design Icons](https://materialdesignicons.com/) libraries.

The attribution for Material Design Icons and Material Design Icons Light currently show "by Austin Andrews." While Austin is the original maintainer, we've moved all attributions of our libraries and tooling to the Pictogrammers group. I'd like to request these two packages be updated to say "by Pictogrammers".

CC: Austin Andrews (@templarian)

Feel free to reach out for any other questions. Thanks.

**Comment by cyberalien** [comment]
Changed. 

Thank you for creating one of the best icon sets!!!

Change will appear tomorrow after icon sets update script runs.
