### ISSUE TITLE
New Icon Set Request: nonicons

### ISSUE THREAD

**Issue by mochaaP** [iconify/icon-sets#75]
- Icon set: Nonicons
- License: MIT
- Repo: <https://github.com/yamatsum/nonicons>

Nonicons are a set of SVG icons representing programming languages, designing & development tools, inspired by Octicons.

As Octicons were already included in iconify, we only need to pull the files in `src/icons/nonicons`.

## Preview

![thumbnail](https://github.com/yamatsum/nonicons/raw/img/src/img/thumbnail.png)

**Comment by cyberalien** [comment]
Added.

It will appear tomorrow after icon sets update.

**Comment by mochaaP** [comment]
@cyberalien Hi, but I don't think the "-16" should be included in the icons name, as they didn't appear in other icon sets.

**Comment by cyberalien** [comment]
It is a set similar to Octicons, which includes various dimensions and has `-16` suffix for 16x16 icons, so I think it is appropriate for that icon set. Maybe other sizes will be added later.

**Comment by mochaaP** [comment]
👌 got it, thanks!

**Comment by mochaaP** [comment]
Oh, another small issue, seems it's missing the `codepoints` table.

Upstream includes it: <https://github.com/yamatsum/nonicons/blob/df0c8daa5d22dfef518264a243eb1fc99a10c10d/.fantasticonrc.js#L9-L364>
