### ISSUE TITLE
Add Arcticons icon set

### ISSUE THREAD

**Issue by jwr12135** [iconify/icon-sets#76]
Icon Set: Arcticons
GitHub Repository: [Donnnno/Arcticons](https://github.com/Donnnno/Arcticons)
License: GPL 3.0

It has over 5000 different icons for many apps and brands. The SVG's are located under [icons/black](https://github.com/Donnnno/Arcticons/tree/main/icons/black) (There's also an icons/white directory, but I think they're the same thing except for the color).

![](https://raw.githubusercontent.com/Donnnno/Arcticons/main/github/header-background.png)

**Comment by jwr12135** [comment]
Actually, there's a few other icon sets that don't show up when I search for them.

**Comment by cyberalien** [comment]
It does. For example, `1111` icon: https://icon-sets.iconify.design/?query=1111

Main search searches icons, not icon sets. To filter icon sets, there is a filter field on right side below main search

**Comment by jwr12135** [comment]
Actually, it is searching correctly, never mind.
