### ISSUE TITLE
Clarity SVG icons

### ISSUE THREAD

**Issue by jcubic** [iconify/icon-sets#79]
I'm the author of Clarity icons, their primary purpose is for GTK+ Linux desktops but they can be used for different things like for Web apps.

https://github.com/jcubic/clarity

The icons are monoshape but in the build script, there are additional dynamic elements added. Also, you can change colors but if you are interested only in shapes then use directories inside the src directory.

Since all icons in the source directory is a single path where all data is in `d` attribute.

**Comment by cyberalien** [comment]
Sorry, but no.

That is a very badly designed icon set. Icons don't follow any logical grid, just vector images resized to fit in 128x128 box with seemingly random padding on sides. It is not maintained, with last big additions made 5 years ago.
