### ISSUE TITLE
Add IconaMoon icons

### ISSUE THREAD

**Issue by slavamak** [iconify/icon-sets#81]
I use these icons in my projects as raw svg, but I would like to use them with iconify. These icons haven't been updated for a long time but they look great and are well designed. There are also a few variations of the icons. The repository author has mentioned that we can use the icons however we want. Any chance you could add this set?

https://github.com/dariushhpg1/IconaMoon

**Comment by cyberalien** [comment]
At quick glance it looks good, but there is no mention of a valid open source license.

However, there is a Figma file, which is a source for that repository and it shows that license is `CC BY 4.0`.

So probably it can be added. I'll need to test it

**Comment by cyberalien** [comment]
Added.

It will appear in icon sets tomorrow.

**Comment by slavamak** [comment]
@cyberalien thank you!
