### ISSUE TITLE
Folder icon replaced by Bedtime Off icon from Material Symbols

### ISSUE THREAD

**Issue by b0oml** [iconify/icon-sets#83]
Hey,

It seems like the **Folder** icon (outlined) has been replaced by the **Bedtime Off** icon from **Material symbols**.

https://icon-sets.iconify.design/material-symbols/folder-outline/

![image](https://github.com/iconify/icon-sets/assets/23080994/33e08558-7421-4931-b6b6-933ec20571fc)

**Comment by cyberalien** [comment]
It's a bug in Material Symbols source.

Source icon: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/folder/default/24px.svg

Reported to their repository, it will be automatically fix whenever they fix it: https://github.com/google/material-design-icons/issues/1522

**Comment by cyberalien** [comment]
It might take a while for Google team to fix stuff, so I've temporarily overwritten that icon with correct older version in today's update.
