### ISSUE TITLE
Inconsistent icon scale in `@iconify-json/prime`

### ISSUE THREAD

**Issue by danielwaltz** [iconify/icon-sets#90]
Hello! Firstly just want to thank you for your work on Iconify, this library is not something I take for granted and it has helped me tremendously over the years!

Just wanted to mention that I noticed some inconsistencies with icon scaling in `@iconify-json/prime`. I am pretty sure that the scale issues are from the [source icons](https://github.com/primefaces/primeicons/tree/master/raw-svg), but you can see in the screenshot below how the `calendar` and `send` icons fall outside the viewport bounds that most other Prime icons fall in to (like `plus` and `apple` in this case).

<img width="323" alt="inconsistent-prime-icon-scaling" src="https://github.com/iconify/icon-sets/assets/2197883/bc84675a-c106-429d-a701-80b9f6bcd550">

My plan is to create an issue in the `primeicons` repo related to this and reference this issue there to hopefully get things moving towards a fix. If this is noisy, feel free to close this issue for now and we can reopen when/if it is resolved upstream!

**Comment by cyberalien** [comment]
Sorry for delay. Missed this issue.

Actually icons in that set have big padding around them, so viewport bounds are not what you think. Select actual icon node to see its size.

For example, this is calendar icon: https://github.com/primefaces/primeicons/blob/master/raw-svg/calendar.svg

I suspect you are using UnoCSS? If so, it scales icons to 1.2em by default. That might give impression that icons are bigger than they actually are.

**Comment by danielwaltz** [comment]
That makes sense. I knew the icon set had padding baked in, but I think the inconsistency around the amount of that padding (whether intentional or not) is on the source files and not related to Iconify.

You are correct that I am using unocss, and I actually didn't realize that it adjusts scale by default! I'll have to make sure that isn't impacting things either.

Thank you for the response! Will close for now.
