### ISSUE TITLE
Want to add LightIcons Set to Iconify Icons Set

### ISSUE THREAD

**Issue by kartikeysharmaks** [iconify/icon-sets#91]
LightIcons Set - https://github.com/lightvue/light-icons/tree/master/svg-light
Prefix - "light-icon"
License - https://github.com/lightvue/light-icons/blob/master/LICENSE

**Comment by cyberalien** [comment]
That is a clone of old version of Tabler Icons with `stroke-width` set to 1, not a unique icon set.

Those "authors" haven't designed anything and didn't even give credit to original authors, added their own copyright even though stuff is not theirs.
