### ISSUE TITLE
Add New Twitter Logo

### ISSUE THREAD

**Issue by ac12644** [iconify/icon-sets#93]
The current Twitter logo used is outdated. As Twitter has updated its branding, please consider adding new logo icon from given link: [https://about.twitter.com/en/who-we-are/brand-toolkit](https://about.twitter.com/en/who-we-are/brand-toolkit
)

**Comment by cyberalien** [comment]
You need to create issues at repositories for icon sets that have older Twitter logos.

Each icon set has a link to source repository. When author of icon set updates logo, it will be automatically updated in Iconify too.
