### ISSUE TITLE
Show more icons per page

### ISSUE THREAD

**Issue by dy** [iconify/icon-sets#96]
Say I am looking for close icon:
<img width="754" alt="image" src="https://github.com/iconify/icon-sets/assets/300067/e39025a3-15dc-4210-a343-eb2313db8ad8">
I need to navigate 16 pages to see all of 745 results.
Is there a chance to make it less pages, like, just 1?

**Comment by cyberalien** [comment]
Yes, that can and should be improved.

You can also click dots in top right corner of icons list to switch to grid mode, which will make browsing icons a bit easier. Though I guess you switched to list mode to see icon sizes and/or names?

**Comment by dy** [comment]
I switched hoping there will be less pages )

**Comment by cyberalien** [comment]
Implemented in new version.

Pagination is now completely dynamic, based on how many items fit in view. It is also scrollable.

Hoping to finish new website before end of this year, but realistically might be delayed by a month or so.
