### ISSUE TITLE
Add MynaUI Icon Set

### ISSUE THREAD

**Issue by praveenjuge** [iconify/icon-sets#97]
License: MIT
Website: https://icons.mynaui.com/
Repo: https://github.com/praveenjuge/mynaui-icons
Icons SVG: https://github.com/praveenjuge/mynaui-icons/tree/main/icons
React Package: https://www.npmjs.com/package/@mynaui/icons-react
Figma File: https://www.figma.com/community/file/1294009455322332728

Let me know if we need anything else!

**Comment by cyberalien** [comment]
Looks very good!

Each icon set has a unique prefix. What do you prefer: `mynaui`, `mynaui-icons` or something else?

**Comment by praveenjuge** [comment]
`mynaui` would be good!

**Comment by cyberalien** [comment]
Added. It will appear tomorrow after update script is ran.

Thank you for creating an excellent icon set!
