### ISSUE TITLE
Some icons are broken

### ISSUE THREAD

**Issue by teppeita** [iconify/icon-sets#99]
I found some icons are broken.

like:
https://icon-sets.iconify.design/material-symbols/sentiment-calm-outline/

It seems to have been unintentionally changed by the following commit.
6f636b7bd70223d8e3479b86bf1893741922f615

So, can you please fix or revert that commit?

**Comment by cyberalien** [comment]
Thanks a lot for reporting!

That's a regression in SVGO 3.0.4, I'll revert back to 3.0.3 and re-run script.

**Comment by cyberalien** [comment]
Reported to SVGO: https://github.com/svg/svgo/issues/1855

All icon sets are being re-parsed right now, using SVGO 3.0.3 for optimisations, should be fixed in about an hour.

**Comment by KTibow** [comment]
Seemingly SVGO 3.0.3 is still being used even though 3.0.5 was published. It would be nice if 3.0.5 could start being used.

**Comment by cyberalien** [comment]
Done. Icon sets re-parsed with 3.1.0 that fixes all issues, all icons seems to look correctly now.
